steps:
  - name: publish_image
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.gnous.eu/${CI_REPO_OWNER}/plakken
      dockerfile: deployement/docker/Dockerfile
      platforms: linux/amd64,linux/arm64/v8,linux/arm
      registry: https://git.gnous.eu
      tag: ${CI_COMMIT}
      username:
          from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push
  - name: publish_image_tag
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.gnous.eu/${CI_REPO_OWNER}/plakken
      dockerfile: deployement/docker/Dockerfile
      platforms: linux/amd64,linux/arm64/v8,linux/arm
      registry: https://git.gnous.eu
      tags:
        - ${CI_COMMIT_TAG##v} # Remove v from tag
        - stable
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event: tag
