steps:
  - name: publish_image
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.gnous.eu/${CI_REPO_OWNER}/plakken
      dockerfile: deployment/docker/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      registry: https://git.gnous.eu
      tag: ${CI_COMMIT_SHA}
      username:
          from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push
      repo: gnouseu/plakken
