steps:
  lint:
    image: golang:1.23
    commands:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - golangci-lint run
    when:
      - event: pull_request
        repo: gnouseu/plakken
      - event: push
        branch: main