steps:
  - name: Release
    image: golang:1.22
    commands:
      - go install github.com/goreleaser/goreleaser@latest
      - goreleaser release
    secrets: [ gitea_token ]
    when:
      event: tag
      repo: gnouseu/plakken
    depends_on: []
  - name: publish_image_tag
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.gnous.eu/${CI_REPO_OWNER}/plakken
      dockerfile: deployment/docker/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      registry: https://git.gnous.eu
      tags:
        - ${CI_COMMIT_TAG##v} # Remove v from tag
        - stable
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event: tag
      repo: gnouseu/plakken
    depends_on: []